import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Toaster
          toastOptions={{
            // Default options for all toasts
            style: {
              background: "#222", // dark background
              color: "#fff", // white text
              boxShadow: "0 4px 14px rgba(0,0,0,0.3)", // subtle shadow
              borderRadius: "8px",
              fontWeight: "500",
              fontSize: "14px",
            },
            success: {
              style: {
                background: "#1e7e34", // dark green for success
                color: "white",
              },
            },
            error: {
              style: {
                background: "#c53030", // dark red for errors
                color: "white",
              },
            },
          }}
        />

        {children}
      </body>
    </html>
  );
}
